# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup
        run: |
          echo sudo apt install libreoffice
          echo wget https://dl.google.com/go/go1.15.8.linux-amd64.tar.gz
          echo sudo tar -C /usr/local -xzf go1.15.8.linux-amd64.tar.gz
                    
      - name: Generate
        run: echo soffice --convert-to pdf docs/test.odt

      - name: Push
        env: # Or as an environment variable
          DRIVE_JSON: ${{ secrets.DRIVE_JSON }}
        run: |
          #/usr/local/go/bin/go get -u github.com/odeke-em/drive/cmd/drive
          echo $DRIVE_JSON > d.json
          ls -al
          echo A
          cat d.json
          echo B
          cat docs/test.odt
          #$HOME/go/bin/drive init --service-account-file d.json
          #$HOME/go/bin/drive push docs
          #$HOME/go/bin/drive pub docs
          rm d.json

          
