# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt install libreoffice
          wget https://dl.google.com/go/go1.15.8.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.15.8.linux-amd64.tar.gz
          /usr/local/go/bin/go
                    
      - name: Generate
        run: soffice --convert-to pdf docs/test.odt

      - name: Push
        run: |
          sudo /usr/local/go/bin/go get -u github.com/odeke-em/drive/cmd/drive
          /usr/local/go/bin/drive

          
